### ISSUE TITLE
add option to change texts color in banner areas from markdown as described here. Reference comment added. 

### ISSUE THREAD

**Issue by devopstoday11** [intelops/website#140]
https://github.com/intelops/website/issues/107#issuecomment-1529432899

```
If I want to change Texts color in the Banner areas, how can I do it?
if you have to change this from markdown then I have to set the option for that.
I set this option for the title and subtitles whare you asked for. please check the markdown content.
if there are no option create an issue, I will do that. 
```

**Comment by tfsojon** [comment]
[added option [enable: true or false] for section/row in OS & platform.](https://github.com/intelops/website/commit/ad820e80ec7b92a38c62a1eb8db4b492bce228c1)

**Comment by tfsojon** [comment]
[added option to change color of OS and Platform banner](https://github.com/intelops/website/commit/76ec752d5985dd2a57f28640d033abb6abd1c215)
