### ISSUE TITLE
menu items not visible on laptop screens with small size. 

### ISSUE THREAD

**Issue by devopstoday11** [intelops/website#172]
@tfsojon 
I observed something new on my 13 inch , 12 inch, and 14 inch laptop screens. On the mobile, I understand there is not screen space, but on laptops (even though small size laptops), there is enough space to show menu items but still not visible. 
Menu items are not visible at all. If the menu bar is empty, then it doesn't make any sense for me to build the style of menu we did. Visitors are loosing lot of valuable information and we will not attract visitors to all content we want. 

I pointed the issue with my mouse pointer in this video - 
https://loom.com/share/f6bf6c9f8472481ca2cde7c55b42baa1

**Comment by devopstoday11** [comment]
@tfsojon

**Comment by tfsojon** [comment]
@devopstoday11
