### ISSUE TITLE
add meta tags

### ISSUE THREAD

**Issue by devopstoday11** [intelops/website#176]
when I checked https://www.opengraph.xyz/ , our website doesn't have any meta tags and preview images.  
Please add meta tags for LinkedIn, FB, Twitter, Discord, Slack, Youtube, etc. 
And also, explain where and how I can add more new meta tags in future myself. 
@tfsojon

**Comment by tfsojon** [comment]
@devopstoday11 

#178

In `params.toml` file you will find metadata block where is the default meta-data for all pages.

![image](https://github.com/intelops/website/assets/87603786/42f843bb-dd45-412e-a764-c5c0173deaa4)
![image](https://github.com/intelops/website/assets/87603786/7c1e9504-b339-43b5-8ea7-d0862ef9015e)

---

and In any page you can set meta info with
```
og_title: "Hello"
og_description: "test description"
og_image: "images/icons/opensource.png"
keywords: ["Intelops", "Cloud-Native", "Ai", "DevOps", "SRE", "Kubernetes", "Talent", "Democratize", "Next-Gen"]
```

![image](https://github.com/intelops/website/assets/87603786/9049c723-6ccd-43f4-b64e-417df3accf2e)
![image](https://github.com/intelops/website/assets/87603786/b78e79c8-b591-4a16-aa3b-36564c3d2bcf)
