### ISSUE TITLE
how to disable a blog or a page from public view and re-enable it whenever ready for public view?

### ISSUE THREAD

**Issue by devopstoday11** [intelops/website#18]
please watch this. I mentioned 3 or 4 different topics in it. 

https://www.loom.com/share/41217279e8ac424790ef4bf38a3613d5

**Comment by tfsojon** [comment]
How to add image-height-width - [check here](https://github.com/intelops/website/issues/17#issuecomment-1314791851)
How to un-publish or disable a page in hugo-site - [check here](https://github.com/intelops/website/issues/17#issuecomment-1314746812)
How to disable disqus feedback/comment globally or by posts - [check here](https://github.com/intelops/website/issues/17#issuecomment-1314742546)

**Comment by tfsojon** [comment]
Here `Data Analytics` on the top is the `series name` 
and on the bottom, the posts are showing from same series.
You provided an example site there posts are showing like this way.

---
![image](https://user-images.githubusercontent.com/87603786/201834383-92a08238-0ef6-4d27-bd0b-28478c240fe3.png)

![image](https://user-images.githubusercontent.com/87603786/201835067-50d7f1ea-7ba2-4c81-bd2f-f30f885699e8.png)

**Comment by devopstoday11** [comment]
This is good. Nice work. That's what I was looking for. Thank you. @tfsojon
