### ISSUE TITLE
setup decapcms for website

### ISSUE THREAD

**Issue by devopstoday11** [intelops/website#203]
https://decapcms.org/ (formerly netlify CMS)

We want to setup netlify CMS (new name DecapCMS) for website so that non-technical user from marketing team can use Decap UI editor to add, update & delete content in the content folder (blogs and learning-center) and also add content on website pages (any page) in all the image & text areas. 
Setup decapcms without depending on netlify authentication i.e., completely offline without needing git-gateway. User should spin up decap on laptop to use decap UI locally. It is possible, decap have steps for it, and some youtube videos also available. ChatGPT can also provide the steps. 
This will help me not needing to add all content myself or only limited people adding content to our site. Everybody who wants to add/edit content will be able to do easily by using decapCMS without knowing how to use hugo or markdown.

**Comment by tfsojon** [comment]
Started working - https://github.com/tfsojon/intelops-website/blob/chandu/static/admin/config.yml
![image](https://github.com/intelops/website/assets/87603786/412d9e42-9d01-423f-8a69-595b42833116)

**Comment by devopstoday11** [comment]
@tfsojon 
added comment in the PR

https://github.com/intelops/website/pull/211#issuecomment-1637318009

**Comment by devopstoday11** [comment]
@tfsojon , also please check this comment from my PR about lottie - 
https://github.com/intelops/website/pull/212#issuecomment-1637711831

**Comment by tfsojon** [comment]
Do you use Discord? Join on discord if possible @sojon
