### ISSUE TITLE
new form pop-up for the button on the home page banner

### ISSUE THREAD

**Issue by devopstoday11** [intelops/website#209]
@tfsojon 
Please use the below details to add a pop-up window where the form will load when the end user clicks the "Join Waitlist" button on the homepage banner. 

```
<iframe class="clickup-embed clickup-dynamic-height" src="https://forms.clickup.com/9006002197/f/8cctc0n-11720/8GEW4HG1M3D5G252CY" onwheel="" width="100%" height="100%" style="background: transparent; border: 1px solid #ccc;"></iframe><script async src="https://app-cdn.clickup.com/assets/js/forms-embed/v1.js"></script>

```

**Comment by tfsojon** [comment]
@devopstoday11 Done in https://github.com/tfsojon/intelops-website/commit/f19e910d2267a6c9626f7d23c715eb6de5b3a2e4
