### ISSUE TITLE
create one separate page to just load the Security Reporting Form

### ISSUE THREAD

**Issue by devopstoday11** [intelops/website#219]
@tfsojon ,
Please create one separate page to load this " Security Vulnerability Reporting " Form. You don't need to add it to any menus. This page should only be accessible as " https://<domain name>/opensource-security-reporting-form/ ". 

```

<iframe class="clickup-embed clickup-dynamic-height" src="https://forms.clickup.com/9006002197/f/8cctc0n-12190/UD4AJPCTSDU2IS70Q0" onwheel="" width="100%" height="100%" style="background: transparent; border: 1px solid #ccc;"></iframe><script async src="https://app-cdn.clickup.com/assets/js/forms-embed/v1.js"></script>

```

In the Banner area, I will add Text. The footer will be as usual, with no change to the Footer area. @tfsojon

**Comment by tfsojon** [comment]
ok

**Comment by tfsojon** [comment]
by removing the border and increasing the max-width of iframe, It might look better.
![image](https://github.com/intelops/website/assets/87603786/97e0af26-d154-4192-9ae6-b42c9486e688)

**Comment by devopstoday11** [comment]
> 

I didn't set any borders. The only option available on the ClickUp Forms setting is "automatically increase the width to fill". 
@tfsojon

**Comment by tfsojon** [comment]
ok make the width fill.
i am adjusting it from the site page.
