### ISSUE TITLE
build case-studies site in our website, similar to blogs site

### ISSUE THREAD

**Issue by devopstoday11** [intelops/website#22]
Hi @tfsojon 
Please fulfill this new req.

https://www.loom.com/share/7d5f051039024ec88df9677fce9c4513 

 
https://snyk.io/blog/category/case-studies/

**Comment by devopstoday11** [comment]
@tfsojon , please do pull a request to your local from the main branch before working on this new requirement. I added the blogs image related items and pushed to main.

**Comment by devopstoday11** [comment]
@tfsojon  - i checked in my local. looks fine so far. will let the marketing team also take a look.

**Comment by devopstoday11** [comment]
@tfsojon 
In the future, if I want to add a link to case-studies to make it publicly visible inside Resources or in the main menu , how to do that?

**Comment by tfsojon** [comment]
in`menu.[-].toml` file you can easily add this. like the screenshot below.
`weight` is for the position of the menu item.

![image](https://user-images.githubusercontent.com/87603786/203757208-5f300e0d-6ef8-4d09-9c52-935b298f883f.png)

**Comment by devopstoday11** [comment]
Thank you, @tfsojon
