### ISSUE TITLE
"updated" parameter is missing

### ISSUE THREAD

**Issue by devopstoday11** [intelops/website#24]
I do see "date" parameter, but "updated" ("update") is missing. Please add that parameter support as well. 

![image](https://user-images.githubusercontent.com/59978378/203729669-5c4afdbb-ed07-4afe-a283-d5f443b361f1.png)

**Comment by tfsojon** [comment]
We don't have to define last update date.
We can get it from `.git`

I added last update in single page. here how it looks. Is it ok?

-----

![image](https://user-images.githubusercontent.com/87603786/203737348-9e8958b9-505d-486f-a2ee-13410066e84d.png)

**Comment by devopstoday11** [comment]
@tfsojon 
Yes, if possible to get it automatically from .git then that's fine.  "Published" and "Last Update" as you showed in the screenshot looks fine. 

Does this mean I can merge your pull request to the main branch? Or, do I have to do anything in my blogs to be able to see "Published" and "Last Update" ?

**Comment by tfsojon** [comment]
Just Merge my last pull req

**Comment by devopstoday11** [comment]
Thank you,  @tfsojon
