### ISSUE TITLE
How to use tabbed feature of Markdown in this hugo site? 

### ISSUE THREAD

**Issue by devopstoday11** [intelops/website#246]
Hi @tfsojon @tfsumon 
If I want to write content (text, image, gif, animation, or anything) in a tabbed structure like the reference below, how do I do that on this website?

Below link is only reference to the tabbed layout:-
https://docs.docker.com/get-started/02_our_app/#build-the-apps-image
https://demo.gethugothemes.com/docbox/ -- this reference is from your templates. Go to "getting started > requirements" to see the tabbed structure. 

This is the same request raised on the docs site - https://github.com/intelops/external-docs/issues/55 

In this template, "Tab" was mentioned - https://demo.gethugothemes.com/godocs/site/style-1/basic-startup/elements/ 
Does it work on both of our main website & docs sites?  @tfsojon @tfsomrat @tfsumon

**Comment by devopstoday11** [comment]
![image](https://github.com/intelops/website/assets/59978378/ce84e756-146b-41c2-a17d-68f0f53cbd78)

**Comment by devopstoday11** [comment]
@tfsojon @tfsomrat 
what is the name of the current website Font? 

And, what is the name of the Font used in this template? 
https://demo.gethugothemes.com/hargo/

**Comment by tfsojon** [comment]
Docbox used - https://fonts.google.com/specimen/IBM+Plex+Mono
Hargo used - https://fonts.google.com/specimen/Quicksand

**Comment by tfsumon** [comment]
Hello @devopstoday11!

I've included the required files to make tabs work on both websites. Now, you can use tabs by adding the following short code into your markdown file.

```
{{< tabs "demo-tab" >}}

{{< tab "first" >}}
First Tab
{{< /tab >}}

{{< tab "second" >}}
Second Tab
{{< /tab >}}

{{< tab "third" >}}
Third Tab
{{< /tab >}}

{{< /tabs >}}
```

**Comment by devopstoday11** [comment]
@tfsumon @tfsojon 
I like this page - https://demo.gethugothemes.com/docbox/  **Getting Started > Requirements**

Is it possible to write content in a similar style to that "Requirements" page in docbox template, in our main website & doc sites as well?

**Comment by devopstoday11** [comment]
@tfsojon @tfsumon ,
I need information on the above query. Is it possible to write the content in similar format as docbox template Requirements page in our current docs site and website? I'm not asking about look & feel. I am asking about the layout the content was presented and how different markdown syntax were used.

**Comment by tfsumon** [comment]
Hi @devopstoday11!

Yes, it's possible, but it will require incorporating those layouts into both our documentation site and website. Please confirm if you would like us to implement this specific layout on your website. Are you referring to the layout shown in the following image?

![image](https://github.com/intelops/website/assets/114845583/d11b865c-902f-4b10-b8e1-2ffcdb0961bd)
![image](https://github.com/intelops/website/assets/114845583/d411c62b-95ae-4508-bcda-4728805ff805)
![image](https://github.com/intelops/website/assets/114845583/c456a58b-43d7-4ba2-b16b-0208f9307770)

**Comment by devopstoday11** [comment]
@tfsumon , yes. 
And also the call to action thing. If all those are available in our website & docs site theme, I will be able to use those layouts and call to action thing wherever I want on different pages. 
Before adding "call to action" thing, please check once if exactly same type of call-to-action thing is available already in our current sites; if available then no need to add call to action thing again.

**Comment by tfsumon** [comment]
Hello @devopstoday11!

I've incorporated those layouts into both sites. You can review these layouts in your local development environment using the following URLs:

- Docsite: `http://localhost:1313/1.0.1/docbox-layouts/`
- Website: `http://localhost:1313/learning-center/docbox-layouts/`

The content file paths are as follows:

- Docsite: `/content/1.0.1/docbox-layouts/`
- Website: `/content/english/learning-center/docbox-layouts/`

**Comment by devopstoday11** [comment]
checked and merged @tfsumon , thank you.
