### ISSUE TITLE
urgent items - Need the Privacy Page and Licensing Page

### ISSUE THREAD

**Issue by devopstoday11** [intelops/website#249]
- create on single page. URL of the page should be like this - " (https://intelops.ai/privacy-policy) ". I want to write the privacy-policy using markdown itself.  Look and feel of this privacy policy page should be something like delta hugo theme single blog page format. 
https://demo.gethugothemes.com/delta/  - go here , click on Pages in the menu and click on "Blog Details". That is the page format I want for our Privacy Policy page. The banner no need to be big; if you go to the https://intelops.ai/contact/ page, see the banner size how slim it is. That kind of slim banner size is enough for Privacy Policy page. This " Privacy Policy " page should go under " Resources in the menu. 

- Make one more copy of learning-center, and name that copy as " Our Policies" & it's URL as - " (https://intelops.ai/licensing-terms-conditions) ". I will add the content and topics myself. This " Our Policies " page should go under " Resources in the menu. 
@tfsojon @tfsumon @tfsomrat Please deliver this [issue ](https://github.com/intelops/website/issues/249) item this weekend itself. It's urgent.

**Comment by devopstoday11** [comment]
@tfsumon 
Please get this done today

**Comment by tfsumon** [comment]
Hello @devopstoday11!

I've started working on it. I will let you know once it's complete.

**Comment by devopstoday11** [comment]
@tfsumon , updates please?

**Comment by tfsumon** [comment]
Hello @devopstoday11!

I apologize for the delayed update. Please check this pr - #250

**Comment by devopstoday11** [comment]
@tfsumon , Thank you. I merged the PR into my branch. First testing looks good so far. I will do more testing and let you know.
