### ISSUE TITLE
sitemap and rss feed for hugo website

### ISSUE THREAD

**Issue by devopstoday11** [intelops/website#25]
Hi @tfsojon ,
When to use sitemap and feed for a website? 
What are the advantage and disadvantages of using them for a website?
And does this Hugo-based website already have both of those?

**Comment by tfsojon** [comment]
Shortly
Sitemaps helps search engines index your site and better understand when new content has been added or updated.
RSS helps users browse your site in an aggregated format without having to visit the site.

Hugo generates both for us
- https://intelops.ai/sitemap.xml
- https://intelops.ai/index.xml

you may read this for better understanding - https://developers.google.com/search/blog/2014/10/best-practices-for-xml-sitemaps-rssatom

**Comment by devopstoday11** [comment]
Thanks @tfsojon 
Good to know that both are in place.
