### ISSUE TITLE
devcontainer.json for this site 

### ISSUE THREAD

**Issue by devopstoday11** [intelops/website#273]
@tfsumon  

I need devcontainer.json for both of our hugo based sites (website and docs site) to make development life easy and to keep the testing dependencies same for everyone. 
Here are the references for devcontainer.json usage - 
https://code.visualstudio.com/docs/devcontainers/create-dev-container#:~:text=The%20dev%20container%20configuration%20is,the%20root%20of%20your%20project. 

https://github.com/microsoft/vscode-dev-containers/tree/main/containers/hugo 

https://github.com/microsoft/vscode-dev-containers/blob/main/containers/hugo/README.md 

https://github.com/microsoft/vscode-dev-containers/blob/main/containers/hugo/.devcontainer/devcontainer.json 

https://www.trollcode.no/blog/2019-09-19-hugo-dev-container/ 

this is very good example which shows how to use devcontainer.json - https://aarynsmith.com/posts/hugo-vscode-docker/

**Comment by tfsumon** [comment]
@devopstoday11 

Added. Please check latest PR.

**Comment by devopstoday11** [comment]
https://github.com/intelops/website/pull/276/commits/fb393bb26218cb4a39a21254651a185313b613f0 

devcontainer json added in this commit.
