### ISSUE TITLE
Tags feature is missing

### ISSUE THREAD

**Issue by devopstoday11** [intelops/website#28]
@tfsojon 
I just realized this when I saw your Reader theme template demo. 
On our current website, in the Blogs & in the Case-Studies sites , the articles are missing the Tags.  Please add that Tags feature and also show me How to mention the Tags in each blog article so that Tags will show up properly for the articles when published. 

![image](https://user-images.githubusercontent.com/59978378/203773934-0ce34432-b93a-468a-b357-bd351dcd8ee7.png)

**Comment by devopstoday11** [comment]
@tfsojon 
Tags are mainly used to easily show all the articles/content which has a particular Tag assigned to them when clicked on a certain Tag name. Same as Categories.

**Comment by tfsojon** [comment]
ok!

**Comment by tfsojon** [comment]
NOTE: `category` should be one and `tags` can be many. ex:

![image](https://user-images.githubusercontent.com/87603786/204073023-bd3e4a1e-aac3-4c0a-97c1-cee69f3e504c.png)


**check `Failed Pixie Deployment On Civo....` post**

![image](https://user-images.githubusercontent.com/87603786/204072894-7f15d0be-963f-4fb0-8885-9b12eba66d3d.png)

**Categories and tags will show in the banner like this way.** - all categories will show first then all tags (as like reader-theme)

![image](https://user-images.githubusercontent.com/87603786/204073068-f505a5b0-cd64-4d46-bea3-75606d80b418.png)

**Comment by devopstoday11** [comment]
@tfsojon 
I want only Categories to be shown in that banner area. Tags should only be shown inside the blog articles on the side.  
Or, another method is to provide titles in that Banner area and properly show them inside that banner; something like this:-
Category: names of each category
Tags: each tag name 
To show the separation of items.

**Comment by devopstoday11** [comment]
@tfsojon 
tags issue 
https://www.loom.com/share/d6b57687f47049ccae7e6f2fecc20c91

**Comment by devopstoday11** [comment]
@tfsojon 
Also, going forward, please submit pull requests to the branch "chandu" instead of to the main branch. That way, I can merge your changes to my branch first, test them locally and then merge to main branch myself.  It makes my testing life easy.

**Comment by devopstoday11** [comment]
@tfsojon 
Is the Tags issue fixed?

**Comment by tfsojon** [comment]
Will work on this today. Please make sure `chandu` branch updated with latest `main` branch.
