### ISSUE TITLE
authentication and authorization on top of hugo?

### ISSUE THREAD

**Issue by devopstoday11** [intelops/website#31]
Hi @tfsojon ,
A different topic....
Is it possible to add authentication (signup/login) and authorization (RBAC or ABAC permissions) on top of a Hugo website using Next.js or React.js ?

**Comment by tfsojon** [comment]
Hello, Never try this with Hugo before. I think it can be possible with some technique, because at the end Hugo generates static html files. But not sure about the future complexity.

**Comment by devopstoday11** [comment]
@tfsojon 
Have you worked on Nextjs framework for generating static websites or dynamic websites , instead of hugo?

**Comment by tfsojon** [comment]
Yes I worked using Nextjs for static sites! Our current website is built with Next.js https://gethugothemes.com/

**Comment by devopstoday11** [comment]
@tfsojon 
Good to know. 
Have you worked on using NextAuthjs for Nextjs website?
Have you developed any project using Nextjs, Strapi, Jamstack, any headless CMS, etc.? Something similar to medium.com and [dev.to](https://dev.to/) and [hashnode](https://hashnode.com/) ?

**Comment by tfsojon** [comment]
I have worked for `SEO optimization` on nextjs and hugo. not worked on authentication and database related task. our other team member do do these things.

**Comment by devopstoday11** [comment]
@tfsojon 
could you please send details of your other team members who did full stack development using nextjs and also any project details I can look at which they worked on.

**Comment by tfsojon** [comment]
@devopstoday11 Please discuss this with our CEO, Mehedi Sharif.

**Comment by devopstoday11** [comment]
ok @tfsojon
