### ISSUE TITLE
want to be able to have different footer for each page

### ISSUE THREAD

**Issue by devopstoday11** [intelops/website#42]
@tfsojon 
As of now, the footer section is common for every page on the website and also the docs site. 
I want to be able to declare different footers for different pages using some markdown file somewhere; if I want to in the future. Please make it possible. 
Note:- I don't plan to have a different footer for each page as of now. But in the future, it is definitely a requirement because of the way we are going to present our content. By the way, the footer content is not going to change; what I want to change is the background color or insert a transparent image as the background for the footer or something like that.  Please add a feature to make this possible. 
Use the chandu branch to submit your PR, please.

**Comment by tfsojon** [comment]
Update footer in 73ce3b693affa1e093f5c87be4dcb59f03d57d80 and f50bd886a6b4cdd3f6997632fbbd74e429c84bb6
if you want to use different style for different pages then need to add this on that page like this - https://github.com/intelops/website/blob/73ce3b693affa1e093f5c87be4dcb59f03d57d80/content/english/_index.md?plain=1#L154-L158

or if you want to change the style for every pages then change it from params.toml
https://github.com/intelops/website/blob/f50bd886a6b4cdd3f6997632fbbd74e429c84bb6/config/_default/params.toml#L17-L21
