### ISSUE TITLE
issue after merging new infinite scrolling PR

### ISSUE THREAD

**Issue by devopstoday11** [intelops/website#46]
@tfsojon  Please help with this issue related to your theme. 

$ hugo server
Start building sites … 
hugo v0.102.3-b76146b129d7caa52417f8e914fc5b9271bf56fc+extended windows/amd64 BuildDate=2022-09-01T10:16:19Z VendorInfo=gohugoio
ERROR 2023/02/25 17:41:43 render of "page" failed: "C:\Users\devops11\Documents\GitHub\website\themes\delta\layouts\_default\how-it-works.html:116:3": execute of template failed: template: _default/how-it-works.html:116:3: executing "main" at <partial "call-to-action-2.html" .>: error calling partial: "C:\Users\devops11\Documents\GitHub\website\themes\delta\layouts\partials\call-to-action-2.html:2:25": execute of template failed: template: partials/call-to-action-2.html:2:25: executing "partials/call-to-action-2.html" at <resources.Get>: error calling Get: dirs not supported resource types: &{0xc000b797d0 0xc001822000}
ERROR 2023/02/25 17:41:43 render of "page" failed: "C:\Users\devops11\Documents\GitHub\website\themes\delta\layouts\_default\mind-map.html:1549:3": execute of template failed: template: _default/mind-map.html:1549:3: executing "main" at <partial "call-to-action-2.html" .>: error calling partial: "C:\Users\devops11\Documents\GitHub\website\themes\delta\layouts\partials\call-to-action-2.html:2:25": execute of template failed: template: partials/call-to-action-2.html:2:25: executing "partials/call-to-action-2.html" at <resources.Get>: error calling Get: dirs not supported resource types: &{0xc0016d9980 0xc0016d6b40}
ERROR 2023/02/25 17:41:43 render of "page" failed: "C:\Users\devops11\Documents\GitHub\website\themes\delta\layouts\_default\baseof.html:41:4": execute of template failed: template: _default/single.html:41:4: executing "_default/single.html" at <partial "footer.html" .>: error calling partial: "C:\Users\devops11\Documents\GitHub\website\themes\delta\layouts\partials\footer.html:3:25": execute of template failed: template: partials/footer.html:3:25: executing "partials/footer.html" at <resources.Get>: error calling Get: dirs not supported resource types: &{0xc0018d73e0 0xc0018a9040}
ERROR 2023/02/25 17:41:43 render of "page" failed: "C:\Users\devops11\Documents\GitHub\website\themes\delta\layouts\_default\optimizor.html:118:3": execute of template failed: template: _default/optimizor.html:118:3: executing "main" at <partial "call-to-action-2.html" .>: error calling partial: "C:\Users\devops11\Documents\GitHub\website\themes\delta\layouts\partials\call-to-action-2.html:2:25": execute of template failed: template: partials/call-to-action-2.html:2:25: executing "partials/call-to-action-2.html" at <resources.Get>: error calling Get: dirs not supported resource types: &{0xc002279e30 0xc0018fadc0}
Error: Error building site: failed to render pages: render of "page" failed: "C:\Users\devops11\Documents\GitHub\website\themes\delta\layouts\_default\contact.html:83:3": execute of template failed: template: _default/contact.html:83:3: executing "main" at <partial "call-to-action-2.html" .>: error calling partial: "C:\Users\devops11\Documents\GitHub\website\themes\delta\layouts\partials\call-to-action-2.html:2:25": execute of template failed: template: partials/call-to-action-2.html:2:25: executing "partials/call-to-action-2.html" at <resources.Get>: error calling Get: dirs not supported resource types: &{0xc00109e3f0 0xc001224000}
Built in 1307 ms

**Comment by tfsojon** [comment]
Hi @devopstoday11 
I checked, and in my terminal it has no issue. also I couldn't found anything that creates this error.
**Could you please send the merged file by creating a ZIP file?**

Thanks

![image](https://user-images.githubusercontent.com/87603786/221395290-5b19e1cb-d022-46d2-93b2-3ba0ca282190.png)

**Comment by devopstoday11** [comment]
@tfsojon could you please pull the latest Chandu branch and try with it and let me know?

**Comment by tfsojon** [comment]
ok I will check

**Comment by devopstoday11** [comment]
https://github.com/intelops/website/commits/chandu 
PR 44 & 45 are what I merged. @tfsojon

**Comment by devopstoday11** [comment]
@tfsojon  I am still facing same issue with Chandu branch. Did you pull new Chandu branch updates and try?

**Comment by tfsojon** [comment]
Yes, I did. I also tried on windowsOS and it's working. So I can make sure that there is no issue on the code.

**Comment by devopstoday11** [comment]
yeah, please check the code and let me know @tfsojon

**Comment by tfsojon** [comment]
There is no Issue in code. I checked the code on MAC and Windows both.

**Comment by devopstoday11** [comment]
I am facing this issue on mac and linux as well @tfsojon 
Only for Chandu branch.

**Comment by devopstoday11** [comment]
@tfsojon please check this https://github.com/intelops/website/pull/45#issuecomment-1448043599

**Comment by tfsojon** [comment]
@devopstoday11 merge the pull req now. added some condition in some of the parameters.
BTW: which Hugo version you are using? also you can delete the chandu1 branch after checking this.

**Comment by devopstoday11** [comment]
@tfsojon able to see the site in my local using chandu branch. closing this issue.
