### ISSUE TITLE
how to disable and enable pages and/or content from public view?

### ISSUE THREAD

**Issue by devopstoday11** [intelops/website#51]
Hi @tfsojon 
How could I enable/disable any page I want from public view? And also, how can I hide/show in the main menu bar in the header area?

I want to be able to hide certain pages or certain sections in a particular page that are not ready. How can I do that?

**Comment by tfsojon** [comment]
- To hide a page set `draft: true` in frontMatter
![image](https://user-images.githubusercontent.com/87603786/223315517-e10f606c-40ff-4a84-9dc0-dba779b72b04.png)

- most of the section are has option to disable
- and for menu comment out the menu item in `menus.[].toml` file like this
![image](https://user-images.githubusercontent.com/87603786/223315457-25cfc41e-530f-4be8-a4b2-c7126eba85a2.png)

**Comment by devopstoday11** [comment]
Thank you. Found it. It's in the config/_default/menus.en.toml file
